Repository magang-mknows/kg, pull requests merged in 2023-03, with the labels that each got.

#2 improvement: mystudy discussion
  src/components/DiscussionMyStudy/cardDiscussion.tsx
  src/components/DiscussionMyStudy/popupEditDiscussion.tsx
  src/components/DiscussionMyStudy/type.d.ts
  src/hooks/Common/usePopupEditDiscussion.ts
  src/hooks/MyStudy/useChooseSidebar.ts
  src/hooks/MyStudy/useDiscussion.ts
  src/modules/MyStudy/Discussion/content.tsx
  src/modules/MyStudy/Discussion/index.tsx
  src/modules/MyStudy/Discussion/sidebar.tsx
  src/pages/studi-ku/[matkul]/diskusi/index.tsx
  src/stores/MyStudy/Discussion/index.tsx
  src/stores/MyStudy/Discussion/type.d.ts
  src/utilities/constant/index.ts
Labels: enhancement

#8 feature : save quiz timer to localStorage
  package.json
  src/components/Navbar/UpperSection.tsx
  src/components/Navbar/index.tsx
  src/hooks/MyStudy/types.d.ts
  src/hooks/MyStudy/useCountDownTimer.ts
  src/hooks/MyStudy/useCurrentQuizNumber.ts
  src/hooks/MyStudy/useQuizQuestion.ts
  src/modules/MyStudy/Quiz/AfterQuiz/QuizScore/NavigationControl.tsx
  src/modules/MyStudy/Quiz/AfterQuiz/QuizScore/Score.tsx
  src/modules/MyStudy/Quiz/StartQuiz/QuizStart.tsx
  src/modules/MyStudy/Quiz/StartQuiz/QuizTimer.tsx
  src/pages/studi-ku/[matkul]/quiz/nilai-quiz/index.tsx
  src/stores/MyStudy/index.tsx
  src/stores/MyStudy/type.d.ts
  yarn.lock
Labels: enhancement

#9 improvement: responsive landing page
  public/bg-hero.svg
  public/bg-landing.png
  src/assets/landing/bg-hero.svg
  src/components/PatnerAction/index.tsx
  src/modules/Landing/AboutSection.tsx
  src/modules/Landing/ChooseStudyProgram.tsx
  src/modules/Landing/HeroSection.tsx
  src/modules/Landing/InformationBanner.tsx
  src/modules/Landing/InformationSection.tsx
  src/modules/Landing/PatnerSection.tsx
  src/modules/Landing/PromotionBanner.tsx
  src/modules/Landing/SekilasSection.tsx
  src/modules/Landing/TestimonySection.tsx
  tailwind.config.js
Labels: documentation

#13 improveemnt: discussion mystudy
  src/assets/diskusi/delete.svg
  src/components/DiscussionMyStudy/cardComment.tsx
  src/components/DiscussionMyStudy/cardDiscussion.tsx
  src/components/DiscussionMyStudy/likeComment.tsx
  src/components/DiscussionMyStudy/popupEditDiscussion.tsx
  src/components/DiscussionMyStudy/type.d.ts
  src/hooks/Common/usePopupDeleteDiscussion.ts
  src/hooks/Common/usePopupEditDiscussion.ts
  src/modules/MyStudy/Discussion/content.tsx
  src/modules/MyStudy/Discussion/sidebar.tsx
  src/stores/Common/index.ts
  src/stores/MyStudy/Discussion/index.tsx
  src/stores/MyStudy/Discussion/type.d.ts
Labels: enhancement

#11 improvement : page guide video and dynamic guide video
  src/components/Footbar/index.tsx
  src/modules/GuideVideo/ContentSection.tsx
  src/modules/Leaderboard/index.tsx
  src/modules/RegistrationVideo/ContentSection.tsx
  src/modules/RegistrationVideo/Description.tsx
  src/modules/RegistrationVideo/ListVideo.tsx
  src/pages/dashboard/papan-skor/index.tsx
  src/stores/Guide/index.ts
  src/utilities/constant/index.ts
Labels: enhancement

#12 feature: add Popup Discussion
  src/components/Common/Modal.tsx
  src/components/Common/TextField.tsx
  src/components/Common/types.d.ts
  src/hooks/Discussion/usePopupCreateDiscussionStatus.ts
  src/hooks/Discussion/usePopupDeleteDiscussionStatus.ts
  src/hooks/Discussion/usePopupEditDiscussionStatus.ts
  src/modules/DiscussionRoom/Content/Search.tsx
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/CreateDiscussion.tsx
  src/modules/DiscussionRoom/CreateDiskusi.tsx
  src/modules/DiscussionRoom/EditDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalCreateDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalDeleteDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalEditDiscussion.tsx
  src/pages/acara-kampus/index.tsx
  src/stores/Common/index.ts
Labels: enhancement

#14 Improvement: migrate to global state (Course section)
  src/modules/MyStudy/Course/CourseHome.tsx
  src/stores/MyStudy/Course.ts
  src/stores/MyStudy/type.d.ts
Labels: enhancement

#16 improvement: dynamic routing reshedule simulation
  src/components/DiscussionMyStudy/cardDiscussion.tsx
  src/hooks/Simulation/useScheduleSimulation.ts
  src/modules/DrillSimulasion/SimulationHistory.tsx
  src/modules/DrillSimulasion/SimulationSubmission.tsx
  src/modules/RescheduleSimulation/content.tsx
  src/modules/RescheduleSimulation/rules.tsx
  src/pages/drill-simulasi/[title].tsx
  src/pages/perubahan-jadwal/[title].tsx
  src/stores/Simulation/index.tsx
  src/stores/Simulation/type.d.ts
Labels: enhancement

#17 fix tab link detail kontrak studi and path modal
  src/components/StudyPlan/TabelDetailContract.tsx
  src/components/StudyPlan/TabelPretest.tsx
  src/components/StudyPlan/types.d.ts
  src/modules/Assigment/BannerSection.tsx
  src/modules/Assigment/ContentSection.tsx
  src/modules/StudyPlan/DetailKontrak/Contract.tsx
  src/modules/StudyPlan/DetailKontrak/index.tsx
Labels: bug

#18 improvement: fix responsive landing
  src/layouts/Base/index.tsx
  src/layouts/Base/types.d.ts
  src/modules/Landing/HeroSection.tsx
  src/modules/Landing/InformationSection.tsx
  src/modules/Landing/SekilasSection.tsx
  src/modules/Landing/index.tsx
Labels: enhancement

#19 feature: add report detail
  src/components/Common/Modal.tsx
  src/components/DiscussionMyStudy/cardComment.tsx
  src/hooks/Discussion/usePopupReportDiscussionStatus.ts
  src/modules/DiscussionRoom/Content/Post/PostOption.tsx
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/PopupModalDeleteDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalEditDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalReportDiscussion.tsx
  src/stores/Common/index.ts
Labels: enhancement

#23 improvement: add unit test
  .github/workflows/main.yml
  src/components/Administration/Accordion.test.tsx
  src/pages/component-test.tsx
Labels: documentation

#27 improvement: add assigment test
  src/components/Administration/Accordion.test.tsx
  src/components/Administration/Accordion.tsx
  src/components/Assigment/AssigmentCard.test.tsx
Labels: documentation, duplicate, enhancement

#29 improvement: fix modal auth
  src/components/Common/Modal.tsx
  src/pages/index.tsx
Labels: documentation

#30 feature: add new StudyPlan popups
  src/assets/StudyPlan/folder-icon.svg
  src/assets/StudyPlan/info-blue-vector.svg
  src/components/Common/PopupModal.tsx
  src/components/Common/types.d.ts
  src/components/StudyPlan/PopUps/PopupDeleteStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupSubmissionStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupSuccessStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupUploadStudyPlan.tsx
  src/components/StudyPlan/PopUps/UploadDragableFieldStudyPlan.tsx
  src/components/StudyPlan/TabelPretest.tsx
  src/hooks/StudyPlan/usePopupDeleteStudyPlan.ts
  src/hooks/StudyPlan/usePopupSubmissionStudyPlan.ts
  src/hooks/StudyPlan/usePopupSuccessStudyPlan.ts
  src/hooks/StudyPlan/usePopupUploadStudyPlan.ts
  src/pages/rencana-studi/fakultas/[slug].tsx
  src/stores/Common/index.ts
Labels: enhancement

#31 change logo patner to svg
  src/assets/logoPatner/mitra1.png
  src/assets/logoPatner/mitra1.svg
  src/assets/logoPatner/mitra2.png
  src/assets/logoPatner/mitra2.svg
  src/assets/logoPatner/mitra3.png
  src/assets/logoPatner/mitra3.svg
  src/assets/logoPatner/mitra4.png
  src/assets/logoPatner/mitra4.svg
  src/assets/logoPatner/mitra5.png
  src/assets/logoPatner/mitra5.svg
  src/components/PatnerAction/index.tsx
  src/components/StudyPlan/SubmissionContractStudy.tsx
Labels: documentation

#32 improvement : improvement hero section leaderboard-pages
  src/assets/leaderboard/avatar.svg
  src/assets/leaderboard/medal-1.svg
  src/assets/leaderboard/medal-2.svg
  src/assets/leaderboard/medal-3.svg
  src/assets/leaderboard/medal.svg
  src/modules/Leaderboard/ContentSection.tsx
  src/modules/Leaderboard/filter.tsx
  src/modules/Leaderboard/index.tsx
Labels: enhancement

#34 improvement: change font text mobile
  src/components/Assigment/BreadCrumb.tsx
  src/components/StudyPlan/BreadCumb.tsx
  src/pages/tes-component/index.tsx
  src/utilities/constant/index.ts
Labels: enhancement

#35 improve table responsive
  src/components/StudyPlan/SubmissionContractStudy.tsx
Labels: documentation

#36 improvement: fix backgroung Partner section
  src/modules/Landing/InformationSection.tsx
  src/modules/Landing/PatnerSection.tsx
  src/modules/Landing/SekilasSection.tsx
Labels: enhancement

#40 feature : add pop up dark mode and change to underline style in CourseHome
  src/components/Common/Modal.tsx
  src/components/Common/PopupModal.tsx
  src/components/Common/types.d.ts
  src/components/StudyPlan/PopUps/PopupDeleteStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupSubmissionStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupSuccessStudyPlan.tsx
  src/components/StudyPlan/PopUps/PopupUploadStudyPlan.tsx
  src/components/StudyPlan/PopUps/UploadDragableFieldStudyPlan.tsx
  src/modules/MyStudy/Course/CourseHome.tsx
Labels: enhancement

#45 improvement: change position category in mobile
  src/modules/DrillSimulasion/SimulationSubmission.tsx
  src/modules/DrillSimulasion/Title.tsx
Labels: enhancement

#46 feature: add discussion service and hooks
  package.json
  src/assets/discussionRoom/checked.svg
  src/hooks/Discussion/useCreateDiscussion.ts
  src/hooks/Discussion/useGetAllDiscussion.ts
  src/hooks/Discussion/usePopupSuccessDiscussionStatus.ts
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/PopupModalCreateDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalEditDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalSuccessDiscussion.tsx
  src/services/Discussion/index.ts
  src/services/Discussion/types.d.ts
  src/stores/Common/index.ts
  yarn.lock
Labels: enhancement

#47 improvement: add responsive table
  src/components/StudyPlan/SubmissionContractStudy.tsx
Labels: enhancement

#51 feature: fix popup modal hooks
  src/components/Common/Modal.tsx
  src/hooks/Discussion/usePopupCreateDiscussionStatus.ts
  src/hooks/Discussion/usePopupDeleteDiscussionStatus.ts
  src/hooks/Discussion/usePopupEditDiscussionStatus.ts
  src/hooks/Discussion/usePopupReportDiscussionStatus.ts
  src/hooks/Discussion/usePopupSuccessDiscussionStatus.ts
  src/modules/DiscussionRoom/Content/Post/PostOption.tsx
  src/modules/DiscussionRoom/Content/Search.tsx
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/PopupModalCreateDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalDeleteDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalEditDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalReportDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalSuccessDiscussion.tsx
  src/services/Discussion/index.ts
  src/stores/Discussion/index.ts
Labels: enhancement

#54 Improvement: leaderboard pages
  src/assets/leaderboard/building.svg
  src/assets/leaderboard/chat.svg
  src/assets/leaderboard/circle.svg
  src/assets/leaderboard/clock.svg
  src/assets/leaderboard/like.svg
  src/assets/leaderboard/module-four.svg
  src/components/Leaderboard/PopupProfil.tsx
  src/components/Leaderboard/StepLadder.tsx
  src/components/Leaderboard/type.d.ts
  src/hooks/Leaderborad/usePopupProfilLeaderboard.tsx
  src/hooks/Leaderborad/useRankLeaderboard.tsx
  src/modules/Leaderboard/ContentSection.tsx
  src/modules/Leaderboard/RankingSection.tsx
  src/modules/Leaderboard/filter.tsx
  src/modules/Leaderboard/type.d.ts
  src/stores/Common/index.ts
  src/stores/Leaderboard/index.tsx
  src/stores/Leaderboard/type.d.ts
Labels: enhancement

#57 Feature/popup reshedule
  src/components/Common/PopupModal.tsx
  src/components/Common/types.d.ts
  src/components/DiscussionMyStudy/cardComment.tsx
  src/hooks/Simulation/useCategorySimulation.ts
  src/modules/RescheduleSimulation/content.tsx
  src/stores/Simulation/index.tsx
Labels: enhancement

#52 improvement: remove img in popup comment
  src/components/Common/PopupModal.tsx
  src/components/Common/types.d.ts
  src/components/DiscussionMyStudy/cardComment.tsx
Labels: enhancement

#55 feature : add skeleton loading to QuizHome, QuizStart, and CourseHome component.
  src/components/Loading/Course/CourseHomeSkeleton.tsx
  src/components/Loading/Quiz/QuizHistorySkeleton.tsx
  src/components/Loading/Quiz/QuizHomeSkeleton.tsx
  src/components/Loading/Quiz/QuizScoreSkeleton.tsx
  src/components/Loading/Quiz/QuizStartSkeleton.tsx
  src/modules/MyStudy/Course/index.tsx
  src/modules/MyStudy/Quiz/AfterQuiz/index.tsx
  src/modules/MyStudy/Quiz/StartQuiz/index.tsx
  src/modules/MyStudy/Quiz/index.tsx
  src/pages/studi-ku/[matkul]/quiz/riwayat-quiz/index.tsx
Labels: enhancement

#59 feature: create dicussion post
  src/modules/DiscussionRoom/Content/Post/PostOption.tsx
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/PopupModalCreateDiscussion.tsx
  src/services/Api/index.ts
  src/services/Auth/index.ts
  src/services/Discussion/index.ts
Labels: enhancement

#60 improvement: responsive and fiks order rank
  src/modules/Leaderboard/ContentSection.tsx
  src/modules/Leaderboard/RankingSection.tsx
Labels: enhancement

#62 improvement: fix responsive discussion
  src/components/Common/Modal.tsx
  src/modules/DiscussionRoom/Content/Post/PostOption.tsx
  src/modules/DiscussionRoom/Content/Post/index.tsx
  src/modules/DiscussionRoom/Content/Search.tsx
  src/modules/DiscussionRoom/Content/index.tsx
  src/modules/DiscussionRoom/PopupModalCreateDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalDeleteDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalEditDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalReportDiscussion.tsx
  src/modules/DiscussionRoom/PopupModalSuccessDiscussion.tsx
  src/services/Api/index.ts
  src/services/Auth/index.ts
  src/services/Discussion/index.ts
Labels: documentation

#63 improve card blue on landing
  src/assets/landing/icon-hero4.svg
  src/assets/landing/icon-hero5.svg
  src/modules/Landing/CardSection.tsx
  src/modules/Landing/HeroSection.tsx
Labels: documentation

#69 Feature/edit komentar
  src/components/Common/PopupModal.tsx
  src/components/Common/types.d.ts
  src/components/DiscussionMyStudy/cardComment.tsx
Labels: enhancement

#71 improvement: add dark mode penugasan
  src/components/Common/UploadDragbleField.tsx
  src/modules/MyStudy/Penugasan/Status.tsx
Labels: enhancement

#73 fix copy text on sekilas section
  package.json
  src/modules/Landing/HeroSection.tsx
  src/modules/Landing/PatnerSection.tsx
  src/modules/Landing/SekilasSection.tsx
  src/modules/Landing/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: bug, documentation

#67 improvement: set dark mode leaderboard
  src/modules/Leaderboard/ContentSection.tsx
  src/modules/Leaderboard/RankingSection.tsx
  src/modules/Leaderboard/index.tsx
Labels: enhancement

#68 feature : add skeleton loading to QuizHistory component
  src/components/Loading/Quiz/QuizHistorySkeleton.tsx
  src/components/Loading/Quiz/QuizScoreSkeleton.tsx
  src/modules/MyStudy/Course/index.tsx
  src/modules/MyStudy/Quiz/AfterQuiz/QuizHistory/index.tsx
  src/modules/MyStudy/Quiz/AfterQuiz/QuizScore/index.tsx
  src/modules/MyStudy/Quiz/AfterQuiz/index.tsx
  src/modules/MyStudy/Quiz/StartQuiz/QuizStart.tsx
  src/modules/MyStudy/Quiz/StartQuiz/index.tsx
  src/modules/MyStudy/Quiz/index.tsx
  src/pages/studi-ku/[matkul]/index.tsx
  src/pages/studi-ku/[matkul]/quiz/index.tsx
  src/pages/studi-ku/[matkul]/quiz/mulai-quiz/index.tsx
  src/pages/studi-ku/[matkul]/quiz/nilai-quiz/index.tsx
  src/pages/studi-ku/[matkul]/quiz/riwayat-quiz/index.tsx
Labels: enhancement

#74 improvement: add skeleton in assignment
  src/components/Loading/Assigment/BannerSkeleton.tsx
  src/components/Loading/Assigment/Breadcrumb.tsx
  src/components/Loading/Assigment/ContentSkeleton.tsx
  src/modules/Assigment/ContentSection.tsx
  src/modules/Assigment/index.tsx
  src/pages/penugasan/index.tsx
Labels: enhancement

#75 improvement: add logic popup by Id
  src/components/Leaderboard/PopupProfil.tsx
  src/components/Leaderboard/type.d.ts
  src/hooks/Leaderborad/usePopupGetUser.tsx
  src/modules/Leaderboard/RankingSection.tsx
  src/stores/Leaderboard/index.tsx
  src/stores/Leaderboard/type.d.ts
Labels: enhancement

#76 fix copy text all section landing
  src/assets/landing/mahasiswa_kampus-gratis.svg
  src/assets/landing/testimonial-01.svg
  src/assets/landing/testimonial-04.svg
  src/assets/landing/user.png
  src/components/Common/Footer.tsx
  src/components/Footbar/index.tsx
  src/modules/Landing/CardSection.tsx
  src/modules/Landing/ChooseStudyProgram.tsx
  src/modules/Landing/HeroSection.tsx
  src/modules/Landing/InformationBanner.tsx
  src/modules/Landing/InformationSection.tsx
  src/modules/Landing/PromotionBanner.tsx
  src/modules/Landing/SekilasSection.tsx
  src/modules/Landing/TestimonySection.tsx
Labels: documentation

#77 improvement: create simulasion skeleton
  src/components/Loading/Simulasion/SubmissionSkeleton.tsx
  src/components/Loading/Simulasion/TitleSkeleton.tsx
  src/modules/DrillSimulasion/Content.tsx
  src/modules/DrillSimulasion/index.tsx
  src/pages/drill-simulasi/index.tsx
Labels: enhancement

#79 improvement: fix responsive in mobile
  src/components/Loading/MyStudy/StatusSkeleton.tsx
  src/modules/MyStudy/Penugasan/Status.tsx
  src/modules/MyStudy/Penugasan/index.tsx
  src/pages/studi-ku/[matkul]/penugasan-test/index.tsx
Labels: enhancement

#80 Feature/skeleton penugasan
  src/components/Loading/MyStudy/StatusSkeleton.tsx
  src/modules/MyStudy/Penugasan/Status.tsx
  src/modules/MyStudy/Penugasan/index.tsx
  src/pages/studi-ku/[matkul]/penugasan-test/index.tsx
Labels: enhancement

#81 feature: create main event page skeleton loading
  src/components/DiscussionRoom/DetailReport.tsx
  src/components/Loading/Discussion/DiscussionSkeleton.tsx
  src/components/Loading/Event/EventSkeleton.tsx
  src/modules/Event/index.tsx
  src/pages/acara-kampus/index.tsx
Labels: enhancement

#82 improvement: change simulasion skeleton
  src/components/Loading/Simulasion/SimulasionSkeleton.tsx
  src/components/Loading/Simulasion/SubmissionSkeleton.tsx
  src/modules/DrillSimulasion/index.tsx
  src/pages/drill-simulasi/index.tsx
Labels: enhancement

#83 improvement: change suspense error reschedule skeleton
  src/components/Loading/Reshedule/ContentSkeleton.tsx
  src/components/Loading/Reshedule/RescheduleSkeleton.tsx
  src/modules/RescheduleSimulation/content.tsx
  src/modules/RescheduleSimulation/dateTime.tsx
  src/modules/RescheduleSimulation/index.tsx
  src/pages/drill-simulasi/[title].tsx
  src/pages/drill-simulasi/index.tsx
  src/pages/perubahan-jadwal/[title].tsx
Labels: enhancement
